// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type Movie struct {
	ID       int64          `json:"id"`
	Name     string         `json:"name"`
	Year     int32          `json:"year"`
	Director sql.NullString `json:"director"`
	Rating   sql.NullString `json:"rating"`
}

type Review struct {
	ID      int64          `json:"id"`
	UserID  int64          `json:"user_id"`
	MovieID int64          `json:"movie_id"`
	Rating  sql.NullString `json:"rating"`
	Text    sql.NullString `json:"text"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
