// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: suggestions.sql

package db

import (
	"context"
	"database/sql"
)

const createSuggestion = `-- name: CreateSuggestion :one
INSERT INTO suggestions(
    user_id, text
) VALUES(
    (
        SELECT id FROM users
        WHERE username=$1
    ),
    $2
)
RETURNING id, user_id, text
`

type CreateSuggestionParams struct {
	Username string         `json:"username"`
	Text     sql.NullString `json:"text"`
}

func (q *Queries) CreateSuggestion(ctx context.Context, arg CreateSuggestionParams) (Suggestion, error) {
	row := q.db.QueryRowContext(ctx, createSuggestion, arg.Username, arg.Text)
	var i Suggestion
	err := row.Scan(&i.ID, &i.UserID, &i.Text)
	return i, err
}
